#!/bin/sh
# Copyright 2019 Decipher Technology Studios
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

REGION=${REGION:-"us-east-1"}
SECRETS_PATH=${SECRETS_PATH:-"/opt/exhibitor-secrets"}
SECRETS_FILE=${SECRETS_FILE:-"exhibitor"}
IP_ADDR=${IP_ADDR:-"localhost"}
PREFIX=${PREFIX:-"exhibitor"}

: ${BUCKET:? 'Missing $BUCKET. Should be set to the s3 state bucket'}

/exhibitor-wrapper -c s3 --s3region $REGION --s3credentials $SECRETS_PATH/$SECRETS_FILE --s3config $BUCKET:$PREFIX --hostname $IP_ADDR
